#!/bin/sh
# fetch-deps.sh - build cJSON (already vendored) and libcurl from source
# into ./build, so the client can be built without any system packages.
#
# Produces build/lib/libcurl.a and writes build/deps.mk, which the Makefile
# includes automatically. On Windows the static libcurl is built with the
# native schannel TLS backend, so no OpenSSL is needed and the resulting
# binary uses the Windows certificate store.
#
# Environment overrides:
#   CURL_VERSION   libcurl release to build        (default 8.11.1)
#   CURL_URL       override the download URL
#   CURL_SRC_DIR   use an already extracted source tree (skips download)
#   BUILDDIR       output directory                (default build)
#   JOBS           parallel make jobs              (default: cpu count)
#   MAKE           make program                    (default: make/mingw32-make)
#
# Usage: sh scripts/fetch-deps.sh
set -eu

ROOT=$(cd "$(dirname "$0")/.." && pwd)
cd "$ROOT"

BUILDDIR=${BUILDDIR:-build}
CURL_VERSION=${CURL_VERSION:-8.11.1}
CURL_URL=${CURL_URL:-https://curl.se/download/curl-$CURL_VERSION.tar.gz}
CURL_SRC_DIR=${CURL_SRC_DIR:-}

CC=${CC:-cc}
command -v "$CC" >/dev/null 2>&1 || {
    echo "error: C compiler '$CC' not found. Set CC=/path/to/gcc" >&2
    exit 1
}

if [ -z "${MAKE:-}" ]; then
    if command -v make >/dev/null 2>&1; then
        MAKE=make
    elif command -v mingw32-make >/dev/null 2>&1; then
        MAKE=mingw32-make
    else
        echo "error: neither make nor mingw32-make found" >&2
        exit 1
    fi
fi

if [ -z "${JOBS:-}" ]; then
    JOBS=$( (nproc 2>/dev/null) || (sysctl -n hw.ncpu 2>/dev/null) || echo 4 )
fi

mkdir -p "$BUILDDIR/lib" "$BUILDDIR/obj"

# ------------------------------------------------------------------ #
# 1. cJSON - vendored in the repository, just needs compiling         #
# ------------------------------------------------------------------ #
if [ ! -f vendor/cJSON.c ]; then
    echo "error: vendor/cJSON.c is missing." >&2
    echo "       Download it from https://github.com/DaveGamble/cJSON" >&2
    exit 1
fi
echo "==> compiling cJSON"
"$CC" -std=c99 -O2 -Ivendor -c vendor/cJSON.c -o "$BUILDDIR/obj/cJSON.o"

# ------------------------------------------------------------------ #
# 2. libcurl - download and build a static library                    #
# ------------------------------------------------------------------ #
if [ -z "$CURL_SRC_DIR" ]; then
    srcdir="$BUILDDIR/curl-$CURL_VERSION"
    tarball="$BUILDDIR/curl-$CURL_VERSION.tar.gz"

    if [ ! -d "$srcdir" ]; then
        if [ ! -f "$tarball" ]; then
            echo "==> downloading $CURL_URL"
            if command -v curl >/dev/null 2>&1; then
                curl -fL --retry 5 -o "$tarball" "$CURL_URL"
            elif command -v wget >/dev/null 2>&1; then
                wget -O "$tarball" "$CURL_URL"
            elif command -v python3 >/dev/null 2>&1; then
                python3 -c "import urllib.request,sys; urllib.request.urlretrieve(sys.argv[1], sys.argv[2])" "$CURL_URL" "$tarball"
            else
                echo "error: no downloader available (curl/wget/python3)" >&2
                exit 1
            fi
        fi
        echo "==> extracting $tarball"
        tar -xzf "$tarball" -C "$BUILDDIR"
    fi
    CURL_SRC_DIR=$srcdir
fi

[ -f "$CURL_SRC_DIR/configure" ] || {
    echo "error: $CURL_SRC_DIR does not look like a libcurl source tree" >&2
    exit 1
}

echo "==> configuring libcurl ($CURL_SRC_DIR)"
cd "$CURL_SRC_DIR"
# A minimal build: no programs, no tests, no SSH/LDAP, schannel for TLS.
./configure \
    --disable-shared --enable-static \
    --disable-debug --disable-curldebug \
    --enable-http --enable-https --disable-ftp --disable-file --disable-ldap \
    --disable-ldaps --disable-rtsp --disable-dict --disable-telnet --disable-tftp \
    --disable-pop3 --disable-imap --disable-smtp --disable-smtps --disable-gopher \
    --disable-mqtt --disable-manual \
    --disable-threaded-resolver \
    --without-ssl --with-schannel \
    --without-brotli --without-zstd --without-libpsl --without-libidn2 \
    --without-librtmp --without-nghttp2 --without-ngtcp2 --without-nghttp3 \
    --without-libssh2 \
    --prefix="$ROOT/$BUILDDIR" \
    CC="$CC" \
    CFLAGS="${CFLAGS:--O2}"

echo "==> building libcurl"
"$MAKE" -j"$JOBS" -C lib
"$MAKE" -C lib install

cd "$ROOT"

if [ ! -f "$BUILDDIR/lib/libcurl.a" ] && [ ! -f "$BUILDDIR/lib/libcurl.dll.a" ]; then
    echo "error: libcurl build produced no library in $BUILDDIR/lib" >&2
    exit 1
fi

# ------------------------------------------------------------------ #
# 3. Tell the Makefile where everything is                            #
# ------------------------------------------------------------------ #
cat > "$BUILDDIR/deps.mk" <<EOF
# Generated by scripts/fetch-deps.sh - do not edit.
LIBCURL_CFLAGS := -I$ROOT/$BUILDDIR/include
LIBCURL_LIBS   := -L$ROOT/$BUILDDIR/lib -lcurl
CJSON_OBJ      := $BUILDDIR/obj/cJSON.o
EOF

echo
echo "==> done"
echo "    libcurl : $BUILDDIR/lib/libcurl.a"
echo "    cJSON   : $BUILDDIR/obj/cJSON.o"
echo "    now run : make"
