# Setup-Build.ps1 - prepare everything needed to build the client on Windows
# and write build/local.mk, which the Makefile picks up automatically.
#
# It compiles cJSON and a static libcurl (schannel TLS backend, no OpenSSL)
# using an existing MinGW-w64 toolchain. Use it when you have gcc but no
# MSYS2/Git Bash shell, so scripts/fetch-deps.sh cannot run.
#
# Example:
#   pwsh -File scripts/Setup-Build.ps1 `
#        -Gcc C:\mingw64\bin\gcc.exe `
#        -Make C:\mingw64\bin\mingw32-make.exe `
#        -CurlSource C:\src\curl-8.11.1
#
# -CurlSource may be omitted: the libcurl tarball is then downloaded into
# build/ and extracted.
param(
    [Parameter(Mandatory = $true)][string]$Gcc,
    [string]$Make = '',
    [string]$CurlSource = '',
    [string]$CurlVersion = '8.11.1',
    [string]$CurlUrl = '',
    [int]$Jobs = 0
)

$ErrorActionPreference = 'Stop'
$Root = Split-Path -Parent $PSScriptRoot
Set-Location $Root

if (-not (Test-Path $Gcc)) { throw "gcc not found: $Gcc" }
$Gcc = (Resolve-Path $Gcc).Path
$GccDir = Split-Path $Gcc

if (-not $Make) {
    foreach ($candidate in @('mingw32-make.exe', 'make.exe')) {
        $p = Join-Path $GccDir $candidate
        if (Test-Path $p) { $Make = $p; break }
    }
}
if (-not $Make -or -not (Test-Path $Make)) {
    throw "make not found; pass -Make C:\mingw64\bin\mingw32-make.exe"
}
$Make = (Resolve-Path $Make).Path

if (-not $CurlUrl) { $CurlUrl = "https://curl.se/download/curl-$CurlVersion.tar.gz" }

$buildDir = Join-Path $Root 'build'
New-Item -ItemType Directory -Force -Path $buildDir | Out-Null

# --- 1. cJSON ------------------------------------------------------ #
Write-Host '==> compiling cJSON'
$cjsonObj = Join-Path $buildDir 'obj\cJSON.o'
New-Item -ItemType Directory -Force -Path (Split-Path $cjsonObj) | Out-Null
& $Gcc -std=c99 -O2 -Ivendor -c vendor\cJSON.c -o $cjsonObj
if ($LASTEXITCODE -ne 0) { throw 'cJSON compilation failed' }

# --- 2. libcurl source --------------------------------------------- #
if (-not $CurlSource) {
    $tarball = Join-Path $buildDir "curl-$CurlVersion.tar.gz"
    $CurlSource = Join-Path $buildDir "curl-$CurlVersion"
    if (-not (Test-Path $CurlSource)) {
        if (-not (Test-Path $tarball)) {
            Write-Host "==> downloading $CurlUrl"
            Invoke-WebRequest -Uri $CurlUrl -OutFile $tarball -UseBasicParsing
        }
        Write-Host "==> extracting $tarball"
        python -c "import tarfile,sys; tarfile.open(sys.argv[1]).extractall(sys.argv[2])" $tarball $buildDir
        if ($LASTEXITCODE -ne 0) { throw 'extraction failed (python3 required)' }
    }
}
$CurlSource = (Resolve-Path $CurlSource).Path

# --- 3. libcurl ---------------------------------------------------- #
$curlOut = Join-Path $buildDir 'curl-mingw'
& (Join-Path $PSScriptRoot 'build-curl-mingw.ps1') -SourceDir $CurlSource -OutDir $curlOut -Gcc $Gcc -Jobs $Jobs
if ($LASTEXITCODE -ne 0) { throw 'libcurl build failed' }

# --- 4. build/local.mk --------------------------------------------- #
$mk = @"
# Generated by scripts/Setup-Build.ps1 - do not edit.
CC             := $($Gcc -replace '\\', '/')
LIBCURL_CFLAGS := -I$((Join-Path $curlOut 'include') -replace '\\', '/')
LIBCURL_LIBS   := -L$($curlOut -replace '\\', '/') -lcurl
CJSON_OBJ      := build/obj/cJSON.o
"@
Set-Content -Path (Join-Path $buildDir 'local.mk') -Value $mk -Encoding ASCII

Write-Host ''
Write-Host '==> done'
Write-Host "    libcurl : $curlOut\libcurl.a"
Write-Host "    cJSON   : $cjsonObj"
Write-Host "    make    : $Make"
Write-Host ''
Write-Host 'Build with:'
Write-Host "    & '$Make'"
